#pragma once

// Shared IOCTL contract between user-mode client and kernel-mode driver.
#ifndef WDBL_MEM_DRIVER_DEFAULT_DEVICE_PATH
#define WDBL_MEM_DRIVER_DEFAULT_DEVICE_PATH L"\\\\.\\WinDbgLiteMem"
#endif

#ifndef IOCTL_WDBL_READ_PROCESS_MEMORY
#define IOCTL_WDBL_READ_PROCESS_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_WRITE_PROCESS_MEMORY
#define IOCTL_WDBL_WRITE_PROCESS_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_PING
#define IOCTL_WDBL_PING CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_GET_THREAD_CONTEXT
#define IOCTL_WDBL_GET_THREAD_CONTEXT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_SET_THREAD_CONTEXT
#define IOCTL_WDBL_SET_THREAD_CONTEXT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_QUERY_VIRTUAL_MEMORY
#define IOCTL_WDBL_QUERY_VIRTUAL_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_PROTECT_VIRTUAL_MEMORY
#define IOCTL_WDBL_PROTECT_VIRTUAL_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_ALLOCATE_VIRTUAL_MEMORY
#define IOCTL_WDBL_ALLOCATE_VIRTUAL_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_FREE_VIRTUAL_MEMORY
#define IOCTL_WDBL_FREE_VIRTUAL_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_CREATE_USER_THREAD
#define IOCTL_WDBL_CREATE_USER_THREAD CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80A, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_OPEN_PROCESS_KERNEL_HANDLE
#define IOCTL_WDBL_OPEN_PROCESS_KERNEL_HANDLE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80B, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_CLOSE_KERNEL_HANDLE
#define IOCTL_WDBL_CLOSE_KERNEL_HANDLE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80C, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_SUSPEND_THREAD
#define IOCTL_WDBL_SUSPEND_THREAD CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80D, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_RESUME_THREAD
#define IOCTL_WDBL_RESUME_THREAD CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80E, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_SUSPEND_PROCESS
#define IOCTL_WDBL_SUSPEND_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80F, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_RESUME_PROCESS
#define IOCTL_WDBL_RESUME_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x810, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_TERMINATE_PROCESS
#define IOCTL_WDBL_TERMINATE_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x811, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_GET_WOW64_THREAD_CONTEXT
#define IOCTL_WDBL_GET_WOW64_THREAD_CONTEXT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x812, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_SET_WOW64_THREAD_CONTEXT
#define IOCTL_WDBL_SET_WOW64_THREAD_CONTEXT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x813, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_QUERY_DEBUG_API_SUPPORT
#define IOCTL_WDBL_QUERY_DEBUG_API_SUPPORT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x814, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_QUERY_EPROCESS_IMAGE_NAME_OFFSET
#define IOCTL_WDBL_QUERY_EPROCESS_IMAGE_NAME_OFFSET CTL_CODE(FILE_DEVICE_UNKNOWN, 0x815, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_DEBUG_ACTIVE_PROCESS
#define IOCTL_WDBL_DEBUG_ACTIVE_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x816, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_DEBUG_ACTIVE_PROCESS_STOP
#define IOCTL_WDBL_DEBUG_ACTIVE_PROCESS_STOP CTL_CODE(FILE_DEVICE_UNKNOWN, 0x817, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_WAIT_FOR_DEBUG_EVENT
#define IOCTL_WDBL_WAIT_FOR_DEBUG_EVENT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x818, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_CONTINUE_DEBUG_EVENT
#define IOCTL_WDBL_CONTINUE_DEBUG_EVENT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x819, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_QUERY_PROCESS_LIST
#define IOCTL_WDBL_QUERY_PROCESS_LIST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x81A, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_QUERY_THREAD_LIST
#define IOCTL_WDBL_QUERY_THREAD_LIST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x81B, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_QUERY_MODULE_LIST
#define IOCTL_WDBL_QUERY_MODULE_LIST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x81C, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_QUERY_MEMORY_MAP
#define IOCTL_WDBL_QUERY_MEMORY_MAP CTL_CODE(FILE_DEVICE_UNKNOWN, 0x81D, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_QUERY_CAPABILITIES
#define IOCTL_WDBL_QUERY_CAPABILITIES CTL_CODE(FILE_DEVICE_UNKNOWN, 0x81E, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_READ_PROCESS_MEMORY_EX
#define IOCTL_WDBL_READ_PROCESS_MEMORY_EX CTL_CODE(FILE_DEVICE_UNKNOWN, 0x81F, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_WRITE_PROCESS_MEMORY_EX
#define IOCTL_WDBL_WRITE_PROCESS_MEMORY_EX CTL_CODE(FILE_DEVICE_UNKNOWN, 0x820, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_QUERY_ANTI_DEBUG
#define IOCTL_WDBL_QUERY_ANTI_DEBUG CTL_CODE(FILE_DEVICE_UNKNOWN, 0x821, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_QUERY_DEBUG_REGISTERS
#define IOCTL_WDBL_QUERY_DEBUG_REGISTERS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x822, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_SET_DEBUG_REGISTERS
#define IOCTL_WDBL_SET_DEBUG_REGISTERS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x823, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_QUERY_HANDLE_LIST
#define IOCTL_WDBL_QUERY_HANDLE_LIST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x824, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_QUERY_THREAD_INFO
#define IOCTL_WDBL_QUERY_THREAD_INFO CTL_CODE(FILE_DEVICE_UNKNOWN, 0x825, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_QUERY_IMAGE_INFO
#define IOCTL_WDBL_QUERY_IMAGE_INFO CTL_CODE(FILE_DEVICE_UNKNOWN, 0x826, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#ifndef IOCTL_WDBL_QUERY_PROCESS_MITIGATIONS
#define IOCTL_WDBL_QUERY_PROCESS_MITIGATIONS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x827, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif
#ifndef IOCTL_WDBL_QUERY_DRIVER_EVENTS
#define IOCTL_WDBL_QUERY_DRIVER_EVENTS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x828, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#define WDBL_DRIVER_CAP_MEMORY_RW        0x00000001UL
#define WDBL_DRIVER_CAP_MEMORY_RW_EX     0x00000002UL
#define WDBL_DRIVER_CAP_THREAD_CONTEXT   0x00000004UL
#define WDBL_DRIVER_CAP_WOW64_CONTEXT    0x00000008UL
#define WDBL_DRIVER_CAP_MODULE_LIST      0x00000010UL
#define WDBL_DRIVER_CAP_MEMORY_MAP       0x00000020UL
#define WDBL_DRIVER_CAP_DEBUG_API        0x00000040UL
#define WDBL_DRIVER_CAP_DEBUG_REGISTERS  0x00000080UL
#define WDBL_DRIVER_CAP_ANTI_DEBUG       0x00000100UL
#define WDBL_DRIVER_CAP_PROCESS_CONTROL  0x00000200UL
#define WDBL_DRIVER_CAP_HANDLE_LIST      0x00000400UL
#define WDBL_DRIVER_CAP_THREAD_INFO      0x00000800UL
#define WDBL_DRIVER_CAP_IMAGE_INFO       0x00001000UL
#define WDBL_DRIVER_CAP_MITIGATIONS      0x00002000UL
#define WDBL_DRIVER_CAP_EVENTS           0x00004000UL

#define WDBL_PROCESS_NAME_CHARS 260
#define WDBL_MODULE_NAME_CHARS 64

#define WDBL_MEM_DRIVER_CAPABILITY_VERSION 1UL

typedef struct _WDBL_DRIVER_CAPABILITIES_RESULT {
    ULONG Version;
    ULONG Size;
    ULONG CapabilityMask;
    ULONG DebugApiMask;
    ULONG IoctlProtocolVersion;
    ULONG Reserved[7];
} WDBL_DRIVER_CAPABILITIES_RESULT;

typedef struct _WDBL_ENUM_RESULT_HEADER {
    ULONG TotalCount;
    ULONG ReturnedCount;
} WDBL_ENUM_RESULT_HEADER;

typedef struct _WDBL_PROCESS_ENUM_ENTRY {
    ULONG ProcessId;
    ULONG ParentProcessId;
    ULONG SessionId;
    ULONG ThreadCount;
    WCHAR ImageName[WDBL_PROCESS_NAME_CHARS];
} WDBL_PROCESS_ENUM_ENTRY;

typedef struct _WDBL_PROCESS_ENUM_REQUEST {
    ULONG ProcessId;
} WDBL_PROCESS_ENUM_REQUEST;

typedef struct _WDBL_THREAD_ENUM_ENTRY {
    ULONG ProcessId;
    ULONG ThreadId;
    ULONGLONG StartAddress;
    LONG Priority;
    LONG BasePriority;
    ULONG ThreadState;
    ULONG WaitReason;
} WDBL_THREAD_ENUM_ENTRY;

typedef struct _WDBL_HANDLE_ENUM_REQUEST {
    ULONG ProcessId;
    ULONG Flags;
} WDBL_HANDLE_ENUM_REQUEST;

typedef struct _WDBL_HANDLE_ENUM_ENTRY {
    ULONGLONG ObjectAddress;
    ULONGLONG HandleValue;
    ULONG GrantedAccess;
    USHORT ObjectTypeIndex;
    USHORT Attributes;
    ULONG Reserved;
    WCHAR ObjectName[260];
} WDBL_HANDLE_ENUM_ENTRY;

typedef struct _WDBL_THREAD_INFO_REQUEST {
    ULONG ThreadId;
    ULONG Flags;
} WDBL_THREAD_INFO_REQUEST;

typedef struct _WDBL_THREAD_INFO_RESULT {
    ULONG ThreadId;
    ULONG ProcessId;
    ULONGLONG TebBaseAddress;
    ULONGLONG StartAddress;
    ULONGLONG AffinityMask;
    LONG Priority;
    LONG BasePriority;
    LONG ExitStatus;
    ULONG Reserved;
    LONG BasicInfoStatus;
    LONG StartAddressStatus;
} WDBL_THREAD_INFO_RESULT;

typedef struct _WDBL_IMAGE_INFO_REQUEST {
    ULONG ProcessId;
    ULONG Flags;
} WDBL_IMAGE_INFO_REQUEST;

typedef struct _WDBL_IMAGE_INFO_RESULT {
    ULONG ProcessId;
    USHORT Machine;
    USHORT Characteristics;
    ULONG TimeDateStamp;
    ULONG SectionCount;
    ULONG SizeOfHeaders;
    ULONG SizeOfImage;
    ULONG Subsystem;
    ULONGLONG ImageBase;
    ULONGLONG EntryPoint;
    LONG PebStatus;
    LONG HeaderStatus;
} WDBL_IMAGE_INFO_RESULT;

typedef struct _WDBL_PROCESS_MITIGATIONS_REQUEST {
    ULONG ProcessId;
    ULONG Flags;
} WDBL_PROCESS_MITIGATIONS_REQUEST;

typedef struct _WDBL_PROCESS_MITIGATIONS_RESULT {
    ULONG ProcessId;
    ULONG ExecuteFlags;
    UCHAR ProtectionLevel;
    UCHAR ReservedProtection[3];
    ULONG BreakOnTermination;
    ULONG IsWow64;
    LONG ExecuteFlagsStatus;
    LONG ProtectionStatus;
    LONG BreakOnTerminationStatus;
    LONG Wow64Status;
} WDBL_PROCESS_MITIGATIONS_RESULT;

#define WDBL_DRIVER_EVENT_PROCESS 1UL
#define WDBL_DRIVER_EVENT_THREAD  2UL
#define WDBL_DRIVER_EVENT_IMAGE   3UL
#define WDBL_DRIVER_EVENT_MEMORY_PROTECT 4UL
#define WDBL_DRIVER_EVENT_REMOTE_THREAD  5UL

typedef struct _WDBL_DRIVER_EVENT_REQUEST {
    ULONG ProcessId;
    ULONG MaxEvents;
    ULONG Flags;
    ULONG Reserved;
} WDBL_DRIVER_EVENT_REQUEST;

typedef struct _WDBL_DRIVER_EVENT_ENTRY {
    ULONG Type;
    ULONG Flags;
    ULONG ProcessId;
    ULONG ThreadId;
    ULONGLONG Address;
    ULONGLONG Size;
    LONG Status;
    WCHAR Name[260];
} WDBL_DRIVER_EVENT_ENTRY;

typedef struct _WDBL_MODULE_ENUM_ENTRY {
    ULONGLONG BaseAddress;
    ULONGLONG EntryPoint;
    ULONG SizeOfImage;
    WCHAR ModuleName[WDBL_MODULE_NAME_CHARS];
    WCHAR ImagePath[WDBL_PROCESS_NAME_CHARS];
} WDBL_MODULE_ENUM_ENTRY;

typedef struct _WDBL_MEMORY_ENUM_REQUEST {
    ULONG ProcessId;
    ULONGLONG StartAddress;
} WDBL_MEMORY_ENUM_REQUEST;

typedef struct _WDBL_MEMORY_ENUM_ENTRY {
    ULONGLONG BaseAddress;
    ULONGLONG AllocationBase;
    ULONGLONG RegionSize;
    ULONG State;
    ULONG Protect;
    ULONG Type;
    ULONG AllocationProtect;
} WDBL_MEMORY_ENUM_ENTRY;
#define WDBL_DEBUG_API_CREATE_DEBUG_OBJECT 0x00000001UL
#define WDBL_DEBUG_API_DEBUG_ACTIVE_PROCESS 0x00000002UL
#define WDBL_DEBUG_API_WAIT_FOR_DEBUG_EVENT 0x00000004UL
#define WDBL_DEBUG_API_DEBUG_CONTINUE 0x00000008UL
#define WDBL_DEBUG_API_REMOVE_PROCESS_DEBUG 0x00000010UL
#define WDBL_DEBUG_API_REQUIRED \
    (WDBL_DEBUG_API_CREATE_DEBUG_OBJECT | WDBL_DEBUG_API_DEBUG_ACTIVE_PROCESS | \
     WDBL_DEBUG_API_WAIT_FOR_DEBUG_EVENT | WDBL_DEBUG_API_DEBUG_CONTINUE | \
     WDBL_DEBUG_API_REMOVE_PROCESS_DEBUG)

#define WDBL_IOCTL_PROTOCOL_MAGIC 0x4C424457UL
#define WDBL_IOCTL_PROTOCOL_VERSION 1UL
#define WDBL_IOCTL_PROTOCOL_KEY 0x9E3779B9UL

typedef struct _WDBL_IOCTL_PACKET_HEADER {
    ULONG Magic;
    ULONG Version;
    ULONG HeaderSize;
    ULONG PayloadSize;
    ULONG IoControlCode;
    ULONG PayloadChecksum;
    ULONG HeaderChecksum;
} WDBL_IOCTL_PACKET_HEADER;

static ULONG WdblIoctlRol32(ULONG value, ULONG bits) {
    return (value << bits) | (value >> (32 - bits));
}

static ULONG WdblIoctlPayloadChecksum(const void* data, ULONG size) {
    const unsigned char* bytes = (const unsigned char*)data;
    ULONG hash = 0x811C9DC5UL;
    ULONG i;
    for (i = 0; i < size; ++i) {
        hash ^= bytes[i];
        hash *= 0x01000193UL;
    }
    return hash;
}

static ULONG WdblIoctlHeaderChecksum(const WDBL_IOCTL_PACKET_HEADER* header) {
    ULONG hash = 0xA5A55A5AUL;
    hash ^= header->Magic;
    hash = WdblIoctlRol32(hash, 5) ^ header->Version;
    hash = WdblIoctlRol32(hash, 5) ^ header->HeaderSize;
    hash = WdblIoctlRol32(hash, 5) ^ header->PayloadSize;
    hash = WdblIoctlRol32(hash, 5) ^ header->IoControlCode;
    hash = WdblIoctlRol32(hash, 5) ^ header->PayloadChecksum;
    return hash ^ WDBL_IOCTL_PROTOCOL_KEY;
}

static void WdblIoctlCryptPayload(void* data, ULONG size, ULONG ioControlCode) {
    unsigned char* bytes = (unsigned char*)data;
    ULONG key = WDBL_IOCTL_PROTOCOL_KEY ^ ioControlCode ^ (size * 0x45D9F3BUL);
    ULONG i;
    for (i = 0; i < size; ++i) {
        key = key * 1664525UL + 1013904223UL;
        bytes[i] ^= (unsigned char)((key >> 24) ^ (key >> 16) ^ (key >> 8) ^ key);
    }
}

typedef struct _WDBL_PROCESS_MEMORY_READ_REQUEST {
    ULONG ProcessId;
    ULONGLONG Address;
    ULONG Size;
} WDBL_PROCESS_MEMORY_READ_REQUEST;

typedef struct _WDBL_PROCESS_MEMORY_READ_EX_REQUEST {
    ULONG ProcessId;
    ULONGLONG Address;
    ULONG Size;
    ULONG Flags;
} WDBL_PROCESS_MEMORY_READ_EX_REQUEST;

typedef struct _WDBL_PROCESS_MEMORY_READ_EX_RESULT {
    ULONG BytesRead;
    LONG KernelStatus;
    ULONGLONG FaultAddress;
    UCHAR Data[1];
} WDBL_PROCESS_MEMORY_READ_EX_RESULT;

typedef struct _WDBL_PROCESS_MEMORY_WRITE_REQUEST_HEADER {
    ULONG ProcessId;
    ULONGLONG Address;
    ULONG Size;
} WDBL_PROCESS_MEMORY_WRITE_REQUEST_HEADER;

typedef struct _WDBL_PROCESS_MEMORY_WRITE_EX_REQUEST_HEADER {
    ULONG ProcessId;
    ULONGLONG Address;
    ULONG Size;
    ULONG Flags;
} WDBL_PROCESS_MEMORY_WRITE_EX_REQUEST_HEADER;

typedef struct _WDBL_PROCESS_MEMORY_WRITE_EX_RESULT {
    ULONG BytesWritten;
    LONG KernelStatus;
    ULONGLONG FaultAddress;
} WDBL_PROCESS_MEMORY_WRITE_EX_RESULT;

typedef struct _WDBL_THREAD_CONTEXT_REQUEST {
    ULONG ThreadId;
    ULONG ContextFlags;
} WDBL_THREAD_CONTEXT_REQUEST;

typedef struct _WDBL_DEBUG_REGISTERS_REQUEST {
    ULONG ThreadId;
    ULONG Flags;
} WDBL_DEBUG_REGISTERS_REQUEST;

typedef struct _WDBL_DEBUG_REGISTERS_RESULT {
    ULONGLONG Dr0;
    ULONGLONG Dr1;
    ULONGLONG Dr2;
    ULONGLONG Dr3;
    ULONGLONG Dr6;
    ULONGLONG Dr7;
} WDBL_DEBUG_REGISTERS_RESULT;

#define WDBL_WOW64_CONTEXT_i386 0x00010000UL
#define WDBL_WOW64_CONTEXT_CONTROL (WDBL_WOW64_CONTEXT_i386 | 0x00000001UL)
#define WDBL_WOW64_CONTEXT_INTEGER (WDBL_WOW64_CONTEXT_i386 | 0x00000002UL)
#define WDBL_WOW64_CONTEXT_SEGMENTS (WDBL_WOW64_CONTEXT_i386 | 0x00000004UL)
#define WDBL_WOW64_CONTEXT_FLOATING_POINT (WDBL_WOW64_CONTEXT_i386 | 0x00000008UL)
#define WDBL_WOW64_CONTEXT_DEBUG_REGISTERS (WDBL_WOW64_CONTEXT_i386 | 0x00000010UL)
#define WDBL_WOW64_CONTEXT_EXTENDED_REGISTERS (WDBL_WOW64_CONTEXT_i386 | 0x00000020UL)
#define WDBL_WOW64_CONTEXT_FULL (WDBL_WOW64_CONTEXT_CONTROL | WDBL_WOW64_CONTEXT_INTEGER | WDBL_WOW64_CONTEXT_SEGMENTS)
#define WDBL_WOW64_CONTEXT_ALL \
    (WDBL_WOW64_CONTEXT_CONTROL | WDBL_WOW64_CONTEXT_INTEGER | WDBL_WOW64_CONTEXT_SEGMENTS | \
     WDBL_WOW64_CONTEXT_FLOATING_POINT | WDBL_WOW64_CONTEXT_DEBUG_REGISTERS | WDBL_WOW64_CONTEXT_EXTENDED_REGISTERS)
#define WDBL_WOW64_SIZE_OF_80387_REGISTERS 80
#define WDBL_WOW64_MAXIMUM_SUPPORTED_EXTENSION 512

#pragma pack(push, 4)
typedef struct _WDBL_WOW64_FLOATING_SAVE_AREA {
    ULONG ControlWord;
    ULONG StatusWord;
    ULONG TagWord;
    ULONG ErrorOffset;
    ULONG ErrorSelector;
    ULONG DataOffset;
    ULONG DataSelector;
    UCHAR RegisterArea[WDBL_WOW64_SIZE_OF_80387_REGISTERS];
    ULONG Cr0NpxState;
} WDBL_WOW64_FLOATING_SAVE_AREA;

typedef struct _WDBL_WOW64_CONTEXT {
    ULONG ContextFlags;
    ULONG Dr0;
    ULONG Dr1;
    ULONG Dr2;
    ULONG Dr3;
    ULONG Dr6;
    ULONG Dr7;
    WDBL_WOW64_FLOATING_SAVE_AREA FloatSave;
    ULONG SegGs;
    ULONG SegFs;
    ULONG SegEs;
    ULONG SegDs;
    ULONG Edi;
    ULONG Esi;
    ULONG Ebx;
    ULONG Edx;
    ULONG Ecx;
    ULONG Eax;
    ULONG Ebp;
    ULONG Eip;
    ULONG SegCs;
    ULONG EFlags;
    ULONG Esp;
    ULONG SegSs;
    UCHAR ExtendedRegisters[WDBL_WOW64_MAXIMUM_SUPPORTED_EXTENSION];
} WDBL_WOW64_CONTEXT;
#pragma pack(pop)

typedef struct _WDBL_WOW64_THREAD_CONTEXT_REQUEST {
    ULONG ThreadId;
    ULONG ContextFlags;
} WDBL_WOW64_THREAD_CONTEXT_REQUEST;

typedef struct _WDBL_VIRTUAL_MEMORY_QUERY_REQUEST {
    ULONG ProcessId;
    ULONGLONG Address;
} WDBL_VIRTUAL_MEMORY_QUERY_REQUEST;

typedef struct _WDBL_VIRTUAL_MEMORY_PROTECT_REQUEST {
    ULONG ProcessId;
    ULONGLONG Address;
    ULONGLONG Size;
    ULONG NewProtect;
} WDBL_VIRTUAL_MEMORY_PROTECT_REQUEST;

typedef struct _WDBL_VIRTUAL_MEMORY_PROTECT_RESULT {
    ULONG OldProtect;
} WDBL_VIRTUAL_MEMORY_PROTECT_RESULT;

typedef struct _WDBL_VIRTUAL_MEMORY_ALLOCATE_REQUEST {
    ULONG ProcessId;
    ULONGLONG BaseAddress;
    ULONGLONG Size;
    ULONG AllocationType;
    ULONG Protect;
} WDBL_VIRTUAL_MEMORY_ALLOCATE_REQUEST;

typedef struct _WDBL_VIRTUAL_MEMORY_ALLOCATE_RESULT {
    ULONGLONG BaseAddress;
    ULONGLONG Size;
} WDBL_VIRTUAL_MEMORY_ALLOCATE_RESULT;

typedef struct _WDBL_VIRTUAL_MEMORY_FREE_REQUEST {
    ULONG ProcessId;
    ULONGLONG BaseAddress;
    ULONGLONG Size;
    ULONG FreeType;
} WDBL_VIRTUAL_MEMORY_FREE_REQUEST;

typedef struct _WDBL_CREATE_USER_THREAD_REQUEST {
    ULONG ProcessId;
    ULONGLONG StartAddress;
    ULONGLONG Parameter;
    ULONG CreateFlags;
    ULONGLONG StackSize;
    ULONGLONG MaximumStackSize;
} WDBL_CREATE_USER_THREAD_REQUEST;

typedef struct _WDBL_CREATE_USER_THREAD_RESULT {
    ULONG ThreadId;
} WDBL_CREATE_USER_THREAD_RESULT;

typedef struct _WDBL_THREAD_CONTROL_REQUEST {
    ULONG ThreadId;
} WDBL_THREAD_CONTROL_REQUEST;

typedef struct _WDBL_THREAD_CONTROL_RESULT {
    ULONG PreviousSuspendCount;
} WDBL_THREAD_CONTROL_RESULT;

typedef struct _WDBL_PROCESS_CONTROL_REQUEST {
    ULONG ProcessId;
    ULONG ExitStatus;
} WDBL_PROCESS_CONTROL_REQUEST;

typedef struct _WDBL_OPEN_PROCESS_KERNEL_HANDLE_REQUEST {
    ULONG ProcessId;
    ULONG DesiredAccess;
} WDBL_OPEN_PROCESS_KERNEL_HANDLE_REQUEST;

typedef struct _WDBL_OPEN_PROCESS_KERNEL_HANDLE_RESULT {
    ULONGLONG KernelHandle;
} WDBL_OPEN_PROCESS_KERNEL_HANDLE_RESULT;

typedef struct _WDBL_CLOSE_KERNEL_HANDLE_REQUEST {
    ULONGLONG KernelHandle;
} WDBL_CLOSE_KERNEL_HANDLE_REQUEST;

typedef struct _WDBL_DEBUG_API_SUPPORT_RESULT {
    ULONG AvailableMask;
    ULONG RequiredMask;
} WDBL_DEBUG_API_SUPPORT_RESULT;

typedef struct _WDBL_EPROCESS_IMAGE_NAME_OFFSET_RESULT {
    ULONG Offset;
    ULONG NameLength;
    ULONG Confidence;
    CHAR ImageName[16];
} WDBL_EPROCESS_IMAGE_NAME_OFFSET_RESULT;

typedef struct _WDBL_ANTI_DEBUG_QUERY_REQUEST {
    ULONG ProcessId;
    ULONG Flags;
} WDBL_ANTI_DEBUG_QUERY_REQUEST;

typedef struct _WDBL_ANTI_DEBUG_QUERY_RESULT {
    ULONG ProcessId;
    ULONG IsWow64;
    ULONGLONG PebAddress;
    ULONGLONG Wow64PebAddress;
    ULONG BeingDebugged;
    ULONG NtGlobalFlag;
    ULONGLONG DebugPort;
    ULONGLONG DebugObjectHandle;
    ULONG DebugFlags;
    LONG PebStatus;
    LONG DebugPortStatus;
    LONG DebugObjectStatus;
    LONG DebugFlagsStatus;
    ULONGLONG ProcessHeap;
    ULONG HeapFlags;
    ULONG HeapForceFlags;
    LONG HeapStatus;
} WDBL_ANTI_DEBUG_QUERY_RESULT;

typedef struct _WDBL_DEBUG_ACTIVE_PROCESS_REQUEST {
    ULONG ProcessId;
} WDBL_DEBUG_ACTIVE_PROCESS_REQUEST;

typedef struct _WDBL_DEBUG_ACTIVE_PROCESS_STOP_REQUEST {
    ULONG ProcessId;
} WDBL_DEBUG_ACTIVE_PROCESS_STOP_REQUEST;

typedef struct _WDBL_WAIT_FOR_DEBUG_EVENT_REQUEST {
    ULONG TimeoutMilliseconds;
} WDBL_WAIT_FOR_DEBUG_EVENT_REQUEST;

typedef struct _WDBL_CONTINUE_DEBUG_EVENT_REQUEST {
    ULONG ProcessId;
    ULONG ThreadId;
    ULONG ContinueStatus;
} WDBL_CONTINUE_DEBUG_EVENT_REQUEST;

typedef struct _WDBL_DEBUG_EVENT_RESULT {
    ULONG DebugEventCode;
    ULONG ProcessId;
    ULONG ThreadId;
    ULONG FirstChance;
    ULONG ExceptionCode;
    ULONG ExceptionFlags;
    ULONGLONG ExceptionRecord;
    ULONGLONG ExceptionAddress;
    ULONG NumberParameters;
    ULONGLONG ExceptionInformation[15];
    ULONG ExitCode;
    ULONGLONG StartAddress;
    ULONGLONG BaseOfImage;
    ULONG DebugInfoFileOffset;
    ULONG DebugInfoSize;
    ULONGLONG BaseOfDll;
    ULONGLONG NamePointer;
    ULONGLONG UnloadBaseOfDll;
} WDBL_DEBUG_EVENT_RESULT;

